### ISSUE TITLE
Panel open takes you to top of the page.

### ISSUE THREAD

**Issue by Creativenauts** [SubZane/flyPanels#8]
Having a bit of an issue when the panel opens it jumps you to the top of the page. Is there a way so this does not occur?

**Comment by SubZane** [comment]
What browser version and plattform are you using?

**Comment by SubZane** [comment]
Never mind my question. There is one untested solution

Add the following CSS rules:

``` css
.flypanels-container.openleft .flypanels-left {
  position: fixed;
}
.flypanels-container.openleft .flypanels-right {
  position: fixed;
}
```

Then also change the JS on around line 125 to

``` javascript
    var onOpenLeft = function () {
        //document.querySelector('body').classList.add('flypanels-open');
        document.querySelector('html').classList.add('flypanels-open');
        hook('onOpenLeft');
    };
```

That fixes the scrolling problem in Chrome on desktop. However I have no idea of what this does to other platforms or browsers yet :)
